### ISSUE TITLE
Analytics Improvements

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/analytics#3]

**Comment by lpasquali** [comment]
- [ ] naming convention for elastic search indexes, independent from logstash or any elastic beats.
- [ ] logstash loses ability to use variables if ilm options are enabled in the output. 
- [ ] Give  a literal ID to the kibana json object if possible
- [ ] This configuration should work even in environments where elasticsearch is not dedicated to GeoServer only. Check index-pattern names, dashboard and visualizations.

**Comment by lpasquali** [comment]
@randomorder I have difficulties to understand those values one is expressed with ',' and one with '.' also even if I could read them as the same, how is it possible that average is > of max maybe avg is around 75ms and max 2s? 
![Screenshot from 2020-09-29 11-48-51](https://user-images.githubusercontent.com/1780406/94543091-e56e2080-0249-11eb-82ad-26d590e57f24.png)

May I add an issue to fix this and make equivalence of units?

**Comment by randomorder** [comment]
2,6K (max) >> 75 (AVG)

Ok, open an issue
